#!/bin/sh

#description "PROG_DESCR"
#program author "PROG_AUTHOR"
#author "Ryan Brackenbury ryan.brackenbury@gmail.com"

# This is just a stub for starting the service. Definitely are better solutions,
# but this is simple and should work on all UNIX-like systems

PIDFILE="/tmp/SERVICE_NAME.pid"     # Path to where pid should be stored. 
USER="RUN_AS"                       # Default user is nobody
BINPATH="BIN_PATH"                  # Path to bin OR bin name
PROG_NAME="SERVICE_NAME"            # Name of this service

if [ `whoami` != "root" ]; then
    echo "Script must be run as root. Usage: $0 {start|stop}"
    exit 1
fi

case "$1" in
  start)
    if [ -e $PIDFILE ]; then
      echo "$PROG_NAME already running!"
    else
      echo "Starting $PROG_NAME"
      nohup su $USER -s /bin/sh -c "exec $BINPATH" 2>&1 >/dev/null &
      echo -n $! > $PIDFILE
    fi
    ;;
  stop)
    echo "Stopping $PROG_NAME"
    if [ -e $PIDFILE ]; then
      kill -15 `cat $PIDFILE`
      rm -f $PIDFILE
    fi 
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
